### PR TITLE
Check if user is not on a slow connection

### PR DESCRIPTION
**Pull request by batbyR**
Following up from Issue #24 

Check if user uses 2g connection or data saver mode.

### CODE REVIEW

**Comment by kurtextrem** [comment]
Imo it doesn't make sense to stop preloading on a slow network. Especially there a big benefit can be had.

We might increase the delay slightly however.

**Comment by futtta** [comment]
But does the 50:50 apply to desktop (mouseOver) or mobile (which uses the touch events which my gut tell me are not as efficient in predicting a link being followed)?

**Comment by kurtextrem** [comment]
Good question. Let's wait for @dieulot

**Comment by dieulot** [comment]
I’m not sure I have data on the touchstart/click ratio, at least I can’t find it right now. I don’t think it’s worse; users scroll and thus trigger touchstart often but it’s not often on a link on most pages.

In any case, preloading one HTML page on 2G usually won’t clog up the connection, so we’ll leave it.

I was open to disabling it when Data Saver mode is enabled but [I’m not anymore](https://github.com/instantpage/instant.page/issues/24#issuecomment-469652889) for now, sorry.

**Pull request closed without merging**
