### PR TITLE
Add `data-instant` attribute to whitelist an external link

### PR DESCRIPTION
**Pull request by batbyR**
Following up from Issue #5 

Whitelist select external links

### CODE REVIEW

**Comment by scitronboy** [comment]
What about adding `data-instant-allow-external` body option to allow all external links to be whitelisted?

**Comment by batbyR** [comment]
Hi @scitronboy,

I am waiting for an explanation from @dieulot for the external link ban.
Maybe it's a bad idea to prefetch external links we don't know, potentially consuming a lot of bandwith.

If not, I would add your body option to my pull request 👍

**Comment by scitronboy** [comment]
Yes, but for small websites like personal blogs where every link is created by you specifically for your content, then external prefetching might be good. Do you think so?

**Comment by dieulot** [comment]
👍

**Pull request merged**
