### PR TITLE
* Add whitelist mode (enabled via adding `data-instant-whitelist-mode` to body)

### LINKED ISSUE #18: Real Whitelist: allow deactivate plugin for every href
I would like to deactivate for every href and only activate for those with the `data-instant` attribute.

Does it make sense?

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #18

### CODE REVIEW

**Comment by atilacamurca** [comment]
Tell me if I understand correctly. This new configuration is as follows?

```html
<html>
  <body data-instant-whitelist-mode>
    <a href="#1" data-instant>Instant link</a>
    <a href="#2">Not an Instant link</a>
  </body>
</html>
```

**Comment by PikachuEXE** [comment]
@atilacamurca 
Yup the only thing new is the `data-instant-whitelist-mode` on `body`

**Comment by PikachuEXE** [comment]
Any more comments?

**Comment by PikachuEXE** [comment]
Is this good to be merged?

**Comment by PikachuEXE** [comment]
Any update for this change?

**Comment by PikachuEXE** [comment]
Would this PR be merged?

**Comment by dieulot** [comment]
Sorry for letting this hanging.

This won’t get merged, it needs tests. Also we wouldn’t use data-instant-whitelist-mode, probably data-instant-whitelist. Also I’m not 100% sure yet that I want a whitelist.

I also want to revamp the tests before adding tests for a whitelist mode, because the arguments to pass currently are a mess.

So I’m going to do it myself. Thanks for your PR though.

**Comment by PikachuEXE** [comment]
OK would you create a draft PR so interest people can follow?
Just a way to subscribe to update instead of every update in this repo

**Pull request closed without merging**
